In [1]:
getwd()

[1] "/fast/AG_Bunina/Yusuf/Project_Endothelial_and_Stroke/Datasets/Chromatin_and_Gene_Exp/2024_C_A_Mannens_C_et_al/04_02_25"

In [2]:
.libPaths()

[1] "/fast/home/y/ykazci/R/x86_64-unknown-linux-gnu-library/4.3"
[2] "/gnu/store/asn7yfxccx9hqi4afrnw685xw6c6382z-profile/site-library"
[3] "/gnu/store/29x2k7i71g9xq09xmbj1lk515cl7if63-r-minimal-4.4.2/lib/R/library"

In [3]:
here::here()

[1] "/fast/AG_Bunina/Yusuf/Project_Endothelial_and_Stroke/Datasets/Chromatin_and_Gene_Exp/2024_C_A_Mannens_C_et_al/04_02_25"

In [4]:
my_epiregulon_lib <- "/fast/AG_Bunina/Yusuf/Project_Endothelial_and_Stroke/Datasets/Chromatin_and_Gene_Exp/2024_C_A_Mannens_C_et_al/04_02_25/renv/library/linux-rhel-9.4/R-4.4/x86_64-unknown-linux-gnu"

In [5]:
library(magrittr)

In [6]:
# Check if I have AUCell pacakge:

my_epiregulon_lib %>% list.files() %>% gtools::mixedsort() %>% head(10)

 [1] "abind"            "annotate"         "AnnotationDbi"    "AnnotationFilter"
 [5] "AnnotationHub"    "ape"              "aplot"            "askpass"
 [9] "assorthead"       "AUCell"

In [7]:
.libPaths(new = my_epiregulon_lib, include.site = FALSE)

In [8]:
.libPaths()

[1] "/fast/AG_Bunina/Yusuf/Project_Endothelial_and_Stroke/Datasets/Chromatin_and_Gene_Exp/2024_C_A_Mannens_C_et_al/04_02_25/renv/library/linux-rhel-9.4/R-4.4/x86_64-unknown-linux-gnu"
[2] "/gnu/store/29x2k7i71g9xq09xmbj1lk515cl7if63-r-minimal-4.4.2/lib/R/library"

In [9]:
here::here('r_objects') |> list.files()

 [1] "GRNtable_sig_fib_newGRN2022_wk27ack4me1_FROM_DariaB.rds"
 [2] "GeneExpressionMatrix.RDS"
 [3] "GeneExpressionMatrix_used_for_epiregulon.RDS"
 [4] "Pando_coef_DF_as_regulon_DF.RDS"
 [5] "Pando_regulon_df_cell_type_weighted.RDS"
 [6] "PeakMatrix.RDS"
 [7] "PeakMatrix_used_for_epiregulon.RDS"
 [8] "PeakMatrix_w_Pando_used_peak_regions.RDS"
 [9] "TF_activity_chunks"
[10] "TF_scores_PANDO_eGRN_by_AUCELL.RDS"
[11] "TF_scores_PANDO_via_weight_by_clusters.RDS"
[12] "atac_qc_by_BPCells.RDS"
[13] "atac_read_counts_by_BPCells.RDS"
[14] "coef_DF_combined.RDS"
[15] "features_vector_combined.RDS"
[16] "fit_DF_combined.RDS"
[17] "mannens_et_al_seurat_modified.RDS"
[18] "mannens_et_al_seurat_obj.RDS"
[19] "mannens_et_al_w_JOINT_PANDO_eGRNs.RDS"
[20] "mannens_et_al_w_JOINT_PANDO_eGRNs_p_adjusted.RDS"
[21] "mat_rna_norm_pseudobulk.RDS"
[22] "metadata.RDS"
[23] "my_human_pwms_v2.RDS"
[24] "pando_eGRN_chunks_final"
[25] "pca_atac_by_bpcells_package.RDS"
[26] "pca_rna_by_bpcells_package.RDS"
[27] "peaks_granges_for_TF_footprinting_by_BPCells.RDS"
[28] "regulon_w_subset_by_EC.RDS"
[29] "regulon_weighted_by_celltypes.RDS"
[30] "res_vpaFib_famAB_dfs_FROM_DariaB.rds"
[31] "sce_atac_mannens.RDS"
[32] "sce_rna_mannens.RDS"
[33] "tf_activity_by_all_cells_matrix_NORMALIZED.RDS"
[34] "tf_activity_by_cells_matrix.RDS"
[35] "tf_activity_by_clusters_matrix.RDS"
[36] "umap_atac_by_bpcells_package.RDS"
[37] "umap_rna_by_bpcells_package.RDS"

In [10]:
# I will apply epiregulon::Addweight function to my Pando eGRN object to
# calculate cell type specific weights of each TF-RE-TG connections.

In [11]:
epiregulon::addWeights %>% args()

function (regulon, expMatrix = NULL, peakMatrix = NULL, exp_assay = "logcounts",
    peak_assay = "PeakMatrix", method = c("wilcoxon", "corr",
        "MI"), clusters = NULL, exp_cutoff = 1, peak_cutoff = 0,
    block_factor = NULL, aggregation_function = mean, min_targets = 10,
    tf_re.merge = FALSE, aggregateCells = FALSE, useDim = "IterativeLSI_ATAC",
    cellNum = 10, BPPARAM = BiocParallel::SerialParam(progressbar = TRUE))
NULL

======================================================================

From Epiregulon vignette:

Epiregulon estimates the regulatory potential using one of the three measures:
1) correlation between TG and TF or between TG and the product of TF and RE,
2) mutual information between TG and TF expression or between TG and the product of TF and RE, 
3) Wilcoxon test statistics of target gene expression in cells jointly expressing all 3 elements vs cells that do not.

======================================================================

In an input regulon data.frame (or DataFrame), there should be at least three columns.\
two cols are "tf" and "target". Third is "idxATAC", which stores row indices of each peak regions\
in the peak counts matrix.

In [12]:
# load Pando eGRN object:

In [13]:
here::here('r_objects') %>% list.files() %>% grep(x = ., pattern = 'mann', value = TRUE)

[1] "mannens_et_al_seurat_modified.RDS"
[2] "mannens_et_al_seurat_obj.RDS"
[3] "mannens_et_al_w_JOINT_PANDO_eGRNs.RDS"
[4] "mannens_et_al_w_JOINT_PANDO_eGRNs_p_adjusted.RDS"
[5] "sce_atac_mannens.RDS"
[6] "sce_rna_mannens.RDS"

In [14]:
mannens_et_al_w_JOINT_PANDO_eGRNs <- 
    readRDS(here::here('r_objects', 'mannens_et_al_w_JOINT_PANDO_eGRNs_p_adjusted.RDS'))

In [15]:
mannens_et_al_w_JOINT_PANDO_eGRNs

Loading required package: Pando

An object of class "GRNData"
Slot "grn":
A RegulatoryNetwork object based on 1122 transcription factors

1 inferred network: glm_network

Slot "data":
An object of class Seurat
430192 features across 49470 samples within 2 assays
Active assay: RNA (25071 features, 5000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: peaks

In [16]:
# Load single cell exp. objects cotaining RNA and ATAC counts:

GeneExpressionMatrix <- 
    readRDS(here::here('r_objects', 'GeneExpressionMatrix_used_for_epiregulon.RDS'))

PeakMatrix <- 
    readRDS(here::here('r_objects', 'PeakMatrix_used_for_epiregulon.RDS'))

EPIREGULON workflow only keeps TF-taget links with correlation value >= 0.5.

Therefore, I also need to filter Pando coefficients data.frame.


    From tutorial, some arguments set to parameters in the find_module function :

    p_thresh = 0.1,
    nvar_thresh = 2, 
    min_genes_per_module = 1, 
    rsq_thresh = 0.05

    Default values:

    function (object, network = DefaultNetwork(object), p_thresh = 0.05, 
    rsq_thresh = 0.1, nvar_thresh = 10, min_genes_per_module = 5)

In [17]:
Pando:::find_modules.GRNData

function (object, network = DefaultNetwork(object), p_thresh = 0.05,
    rsq_thresh = 0.1, nvar_thresh = 10, min_genes_per_module = 5)
{
    params <- Params(object)
    regions <- NetworkRegions(object)
    net_obj <- GetNetwork(object, network = network)
    net_obj <- find_modules(net_obj, p_thresh = p_thresh, rsq_thresh = rsq_thresh,
        nvar_thresh = nvar_thresh, min_genes_per_module = min_genes_per_module)
    modules <- NetworkModules(net_obj)
    reg2peaks <- rownames(GetAssay(object, assay = params$peak_assay))[regions@peaks]
    names(reg2peaks) <- Signac::GRangesToString(regions@ranges)
    peaks_pos <- modules@features$regions_pos %>% map(function(x) unique(reg2peaks[x]))
    peaks_neg <- modules@features$regions_neg %>% map(function(x) unique(reg2peaks[x]))
    modules@features[["peaks_pos"]] <- peaks_pos
    modules@features[["peaks_neg"]] <- peaks_neg
    object@grn@networks[[network]]@modules <- modules
    return(object)
}
<bytecode: 0x45778d68>
<environment: namespace:Pando>

In [18]:
Pando:::find_modules.Network

function (object, p_thresh = 0.05, rsq_thresh = 0.1, nvar_thresh = 10,
    min_genes_per_module = 5, xgb_method = c("tf", "target"),
    xgb_top = 50, verbose = TRUE)
{
    fit_method <- NetworkParams(object)$method
    xgb_method <- match.arg(xgb_method)
    if (!fit_method %in% c("glm", "cv.glmnet", "glmnet", "brms",
        "xgb")) {
        stop(paste0("find_modules() is not yet implemented for \"",
            fit_method, "\" models"))
    }
    models_use <- gof(object) %>% filter(rsq > rsq_thresh & nvariables >
        nvar_thresh) %>% pull(target) %>% unique()
    modules <- coef(object) %>% filter(target %in% models_use)
    if (fit_method %in% c("cv.glmnet", "glmnet")) {
        modules <- modules %>% filter(estimate != 0)
    }
    else if (fit_method == "xgb") {
        modules <- modules %>% group_by_at(xgb_method) %>% top_n(xgb_top,
            gain) %>% mutate(estimate = sign(corr) * gain)
    }
    else {
        modules <- modules %>% filter(ifelse(is.na(padj), T,
            padj < p_thresh))
    }
    modules <- modules %>% group_by(target) %>% mutate(nvars = n()) %>%
        group_by(target, tf) %>% mutate(tf_sites_per_gene = n()) %>%
        group_by(target) %>% mutate(tf_per_gene = length(unique(tf)),
        peak_per_gene = length(unique(region))) %>% group_by(tf) %>%
        mutate(gene_per_tf = length(unique(target))) %>% group_by(target,
        tf)
    if (fit_method %in% c("cv.glmnet", "glmnet", "xgb")) {
        modules <- modules %>% reframe(estimate = sum(estimate),
            n_regions = peak_per_gene, n_genes = gene_per_tf,
            n_tfs = tf_per_gene, regions = paste(region, collapse = ";"))
    }
    else {
        modules <- modules %>% reframe(estimate = sum(estimate),
            n_regions = peak_per_gene, n_genes = gene_per_tf,
            n_tfs = tf_per_gene, regions = paste(region, collapse = ";"),
            pval = min(pval), padj = min(padj))
    }
    modules <- modules %>% distinct() %>% arrange(tf)
    module_pos <- modules %>% filter(estimate > 0) %>% group_by(tf) %>%
        filter(n() > min_genes_per_module) %>% group_split() %>%
        {
            names(.) <- map_chr(., function(x) x$tf[[1]])
            .
        } %>% map(function(x) x$target)
    module_neg <- modules %>% filter(estimate < 0) %>% group_by(tf) %>%
        filter(n() > min_genes_per_module) %>% group_split() %>%
        {
            names(.) <- map_chr(., function(x) x$tf[[1]])
            .
        } %>% map(function(x) x$target)
    regions_pos <- modules %>% filter(estimate > 0) %>% group_by(tf) %>%
        filter(n() > min_genes_per_module) %>% group_split() %>%
        {
            names(.) <- map_chr(., function(x) x$tf[[1]])
            .
        } %>% map(function(x) unlist(str_split(x$regions, ";")))
    regions_neg <- modules %>% filter(estimate < 0) %>% group_by(tf) %>%
        filter(n() > min_genes_per_module) %>% group_split() %>%
        {
            names(.) <- map_chr(., function(x) x$tf[[1]])
            .
        } %>% map(function(x) unlist(str_split(x$regions, ";")))
    module_feats <- list(genes_pos = module_pos, genes_neg = module_neg,
        regions_pos = regions_pos, regions_neg = regions_neg)
    log_message(paste0("Found ", length(unique(modules$tf)),
        " TF modules"), verbose = verbose)
    module_meta <- select(modules, tf, target, everything())
    object@modules@meta <- module_meta
    object@modules@features <- module_feats
    object@modules@params <- list(p_thresh = p_thresh, rsq_thresh = rsq_thresh,
        nvar_thresh = nvar_thresh, min_genes_per_module = min_genes_per_module)
    return(object)
}
<bytecode: 0x460fc438>
<environment: namespace:Pando>

In [19]:
# I AM HERE !!!!

In [17]:
GeneExpressionMatrix

class: SingleCellExperiment
dim: 20661 49470
metadata(0):
assays(3): counts logcounts scaledata
rownames(20661): WASH9P LINC01409 ... DAZ1 DAZ2
rowData names(2): gene_id gene_name
colnames(49470): 10X280_1:CAGATTCAGCAGCTCA 10X365_2:ACCAATATCAATGACC
  ... 10X346_4:CGCTGTGCACGTAATT 10X406_4:GAGAAACGTGGTGAGA
colData names(92): orig.ident nCount_RNA ... ident
  main_cell_types_renamed
reducedDimNames(3): PCA UMAP_RNA JOINT_UMAP
mainExpName: RNA
altExpNames(0):

In [18]:
PeakMatrix

class: SingleCellExperiment
dim: 405121 49470
metadata(0):
assays(2): counts logcounts
rownames: NULL
rowData names(0):
colnames(49470): 10X280_1:CAGATTCAGCAGCTCA 10X365_2:ACCAATATCAATGACC
  ... 10X346_4:CGCTGTGCACGTAATT 10X406_4:GAGAAACGTGGTGAGA
colData names(91): orig.ident nCount_RNA ... peaks.weight ident
reducedDimNames(2): PCA_ATAC UMAP_ATAC
mainExpName: NULL
altExpNames(0):

In [19]:
Pando_regulon_df <- mannens_et_al_w_JOINT_PANDO_eGRNs %>% coef()

In [20]:
Pando_regulon_df %>% head()

  tf     target region               term                        estimate
1 NFIB   NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:NFIB    0.038513008
2 ZFPM2  NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:ZFPM2  -0.007733542
3 SOX11  NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:SOX11   0.065692288
4 SREBF2 NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:SREBF2 -0.011474373
5 NFIX   NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:NFIX    0.038547242
6 PRDM16 NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:PRDM16  0.102150764
  std_err    statistic  pval        padj       corr
1 0.01176352  3.2739367 0.001061345 0.02420174 0.2650796
2 0.01592443 -0.4856401 0.627224560 0.88962096 0.1124816
3 0.02031582  3.2335530 0.001223423 0.02697227 0.1387585
4 0.01963357 -0.5844262 0.558936340 0.86081834 0.1436841
5 0.02219537  1.7367245 0.082442149 0.40317544 0.2110484
6 0.07533459  1.3559609 0.175117909 0.56993025 0.1478573

In [21]:
PeakMatrix@assays@data$counts %>% rownames() %>% head()

[1] "chr10-100006329-100006730" "chr10-100009751-100010152"
[3] "chr10-100016741-100017142" "chr10-100019766-100020167"
[5] "chr10-100020276-100020677" "chr10-100020877-100021278"

In [22]:
intersect(Pando_regulon_df$region, PeakMatrix@assays@data$counts %>% rownames()) %>% length()

[1] 8295

=================================================================================

Now, for only very few peak regions in Pando regulon DF (coef DF), we could find\
a match in the peak count matrix.

=================================================================================

In [25]:
Pando_regulon_df$region %>% unique() %>% length() # total unique regions in the Pando regulon:

[1] 316798

In [26]:
PeakMatrix@assays@data$counts %>% dim() # total regions and cells:

[1] 405121  49470

In [27]:
intersect(Pando_regulon_df$region, rownames(PeakMatrix@assays@data$counts)) %>% length()

[1] 8295

In [28]:
# retrieve seurat object:

mannens_et_al_seurat <- mannens_et_al_w_JOINT_PANDO_eGRNs@data

In [29]:
mannens_et_al_seurat@assays$peaks %>% rownames() %>% head()

[1] "chr10-100006329-100006730" "chr10-100009751-100010152"
[3] "chr10-100016741-100017142" "chr10-100019766-100020167"
[5] "chr10-100020276-100020677" "chr10-100020877-100021278"

In [30]:
intersect(rownames(PeakMatrix@assays@data$counts), rownames(mannens_et_al_seurat@assays$peaks)) %>% length()

[1] 405121

In [31]:
PeakMatrix@assays@data$counts %>% rownames() %>% class()

[1] "character"

In [32]:
intersect(Pando_regulon_df$region, rownames(mannens_et_al_seurat@assays$peaks)) %>% length()

[1] 8295

Now, for only very few peak regions in Pando regulon DF (coef DF), we could find\
a match in the peak count matrix.

============================================================================================

The reason is that in Pando workflow, I set the option that reformats the peak regions\
joining them with mammalian conserved enhancer regions and SCREEN regions,\
using the following command:

regions = union(phastConsElements20Mammals.UCSC.hg38, SCREEN.ccRE.UCSC.hg38)

Therefore, I need to examine how Pando calculate new peak matrix and need to create\
a new single cell exp. object with this new matrix.

============================================================================================

In [33]:
# Find the relevant Pando function:

methods(generic.function = 'initiate_grn')

[1] initiate_grn.GRNData* initiate_grn.Seurat*
see '?methods' for accessing help and source code

In [34]:
getS3method("initiate_grn", "Seurat")

function (object, regions = NULL, peak_assay = "peaks", rna_assay = "RNA",
    exclude_exons = TRUE)
{
    gene_annot <- Signac::Annotation(object[[peak_assay]])
    if (is.null(gene_annot)) {
        stop("Please provide a gene annotation for the ChromatinAssay.")
    }
    peak_ranges <- StringToGRanges(rownames(Seurat::GetAssay(object,
        assay = peak_assay)))
    if (!is.null(regions)) {
        cand_olaps <- findOverlaps(regions, peak_ranges)
        cand_ranges <- pintersect(peak_ranges[subjectHits(cand_olaps)],
            regions[queryHits(cand_olaps)])
    }
    else {
        cand_ranges <- peak_ranges
    }
    if (exclude_exons) {
        exon_ranges <- gene_annot[gene_annot$type == "exon",
            ]
        names(exon_ranges@ranges) <- NULL
        exon_ranges <- IRanges::intersect(exon_ranges, exon_ranges)
        exon_ranges <- GenomicRanges::GRanges(seqnames = exon_ranges@seqnames,
            ranges = exon_ranges@ranges)
        cand_ranges <- GenomicRanges::subtract(cand_ranges, exon_ranges,
            ignore.strand = TRUE) %>% unlist()
    }
    peak_overlaps <- findOverlaps(cand_ranges, peak_ranges)
    peak_matches <- subjectHits(peak_overlaps)
    regions_obj <- new(Class = "Regions", ranges = cand_ranges,
        peaks = peak_matches, motifs = NULL)
    params <- list(peak_assay = peak_assay, rna_assay = rna_assay,
        exclude_exons = exclude_exons)
    grn_obj <- new(Class = "RegulatoryNetwork", regions = regions_obj,
        params = params)
    object <- new(Class = "GRNData", grn = grn_obj, data = object)
    return(object)
}
<bytecode: 0x155c3c68>
<environment: namespace:Pando>

=================================================================

From the method above, one can appreciate that Pando finds overlaps\
between input genomic ranges of peak regions in the peaks count feature\
names and the "regions" if provided by the user. Then, it stores the\
matching peak ranges' positional indices (in the peak count matrix)\
in the newly created 'regions' object. This 'regions' object stores\
the peak region raw indices in the 'peaks' slot. The new peak regions'\
genomic ranges are stored in the 'ranges' slot of the Refions object.

When infer_eGRN function is run, Pando will take the region names from\
the Regions object and also retrieve the paek counts for each regions by\
indexing the peak counts matrix in the Seurat object using the peaks indices\
in the Region object.

===================================================================

Now, I will create a new peaks matrix for those Pando-used regions.

In [35]:
# access regions object:

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions

An Regions object
with 459186 candidate genomic regions in 306458 peaks

In [36]:
# view ranges:

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges

GRanges object with 459186 ranges and 0 metadata columns:
           seqnames            ranges strand
              <Rle>         <IRanges>  <Rle>
       [1]     chr1     181291-181601      *
       [2]     chr1     184649-184672      *
       [3]     chr1     190865-191043      *
       [4]     chr1     778562-778769      *
       [5]     chr1     817144-817370      *
       ...      ...               ...    ...
  [459182]     chrY 19077417-19077730      *
  [459183]     chrY 19567040-19567385      *
  [459184]     chrY 19744631-19744670      *
  [459185]     chrY 19744940-19744980      *
  [459186]     chrY 20575517-20575724      *
  -------
  seqinfo: 25 sequences from an unspecified genome; no seqlengths

In [37]:
# view indices of overlapping regions for each pando-regions:

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@peaks %>% head()

[1] 154353 155047 155819 176299 176685 176695

In [38]:
# To verify, we can check the number of total regions in the 
# Chromatin assay given initially to Pando:

mannens_et_al_seurat@assays$peaks

ChromatinAssay data with 405121 features for 49470 cells
Variable features: 101285
Genome:
Annotation present: TRUE
Motifs present: FALSE
Fragment files: 0

In [39]:
# We have 405121 features.

# Now, peaks slot should have minimum 1. and maximum 405121. 
# position indices if they have a match or values between them: 

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@peaks %>% summary()

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
      1  101459  204255  203388  305338  405121

In [40]:
# Now, we verified and will create the peak matrix for
# Pnado regions.

In [41]:
mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges %>% Signac::GRangesToString() %>% head()

[1] "chr1-181291-181601" "chr1-184649-184672" "chr1-190865-191043"
[4] "chr1-778562-778769" "chr1-817144-817370" "chr1-818203-818239"

In [42]:
mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@peaks %>% head() %>% dput()

c(154353L, 155047L, 155819L, 176299L, 176685L, 176695L)

In [43]:
mannens_et_al_seurat@assays$peaks$counts[c(154353L, 155047L, 155819L, 176299L, 176685L, 176695L), ] %>% rownames()

[1] "chr1-181291-181692" "chr1-184271-184672" "chr1-190642-191043"
[4] "chr1-778533-778934" "chr1-817144-817545" "chr1-817838-818239"

In [44]:
pando_Peaks_matrix <- PeakMatrix@assays@data$counts

In [45]:
pando_Peaks_matrix %>% head()

  [[ suppressing 34 column names '10X280_1:CAGATTCAGCAGCTCA', '10X365_2:ACCAATATCAATGACC', '10X365_2:ATGGTGCGTCACCTAT' ... ]]

6 x 49470 sparse Matrix of class "dgCMatrix"

chr10-100006329-100006730 . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr10-100009751-100010152 . . . . . . . . 1 . . . . . 1 1 . . 1 1 . . . . 1 . .
chr10-100016741-100017142 . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr10-100019766-100020167 . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr10-100020276-100020677 . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr10-100020877-100021278 . . . . . . . . . . . . . . . . . . . . 2 . . . . . .

chr10-100006329-100006730 . . . . . . . ......
chr10-100009751-100010152 . . 1 . . . . ......
chr10-100016741-100017142 . . . . . . . ......
chr10-100019766-100020167 . . . . . . . ......
chr10-100020276-100020677 . . . . . . . ......
chr10-100020877-100021278 . . . . . . . ......

 .....suppressing 49436 columns in show(); maybe adjust options(max.print=, width=)
 ..............................

In [46]:
# Filter by positions:

peak_indices <- mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@peaks

In [47]:
pando_Peaks_matrix %>% dim()

[1] 405121  49470

In [48]:
peak_indices %>% length()

[1] 459186

In [49]:
# some indices are used more than one.

In [50]:
# filter the matrix:

pando_Peaks_matrix <- pando_Peaks_matrix[peak_indices,]

In [127]:
pando_Peaks_matrix %>% dim()

[1] 459186  49470

In [51]:
pando_Peaks_matrix[1:5,1:5]

5 x 5 sparse Matrix of class "dgCMatrix"
                   10X280_1:CAGATTCAGCAGCTCA 10X365_2:ACCAATATCAATGACC
chr1-181291-181692                         .                         .
chr1-184271-184672                         .                         .
chr1-190642-191043                         .                         .
chr1-778533-778934                         1                         1
chr1-817144-817545                         .                         .
                   10X365_2:ATGGTGCGTCACCTAT 10X280_1:ACACCTTGTCATTAGG
chr1-181291-181692                         .                         .
chr1-184271-184672                         .                         .
chr1-190642-191043                         .                         .
chr1-778533-778934                         .                         .
chr1-817144-817545                         .                         .
                   10X406_1:TATCGCGAGGCTTAAC
chr1-181291-181692                         .
chr1-184271-184672                         .
chr1-190642-191043                         .
chr1-778533-778934                         .
chr1-817144-817545                         .

In [52]:
# Now, I will retrive region names from Pando and use them
# to rename the peak matrix.

# we can see how the peak regions between to overlap:

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges %>% Signac::GRangesToString() %>% head()

[1] "chr1-181291-181601" "chr1-184649-184672" "chr1-190865-191043"
[4] "chr1-778562-778769" "chr1-817144-817370" "chr1-818203-818239"

In [53]:
pando_Peaks_matrix %>% rownames() %>% head(5)

[1] "chr1-181291-181692" "chr1-184271-184672" "chr1-190642-191043"
[4] "chr1-778533-778934" "chr1-817144-817545"

In [54]:
data.frame(old_peaks = pando_Peaks_matrix %>% rownames() %>% head(),
           new_Pando_created_peaks = mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges %>% Signac::GRangesToString() %>% head())

  old_peaks          new_Pando_created_peaks
1 chr1-181291-181692 chr1-181291-181601
2 chr1-184271-184672 chr1-184649-184672
3 chr1-190642-191043 chr1-190865-191043
4 chr1-778533-778934 chr1-778562-778769
5 chr1-817144-817545 chr1-817144-817370
6 chr1-817838-818239 chr1-818203-818239

In [55]:
# check if new-to-be rownames are unique:

mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges %>% Signac::GRangesToString() %>% duplicated() %>% table()

.
 FALSE
459186

In [56]:
# rename the matrix:

rownames(pando_Peaks_matrix) <- mannens_et_al_w_JOINT_PANDO_eGRNs@grn@regions@ranges %>% Signac::GRangesToString()

In [57]:
# Now, I will verify the complete overlap between Pando regulon and peak matrix:

In [58]:
length(Pando_regulon_df$region %>% unique())

[1] 316798

In [59]:
intersect(unique(Pando_regulon_df$region), rownames(pando_Peaks_matrix)) %>% length()

[1] 316798

In [60]:
# Now, I will create a single cell experiment object with the new Pando-peak matrix:

In [61]:
PeakMatrix_PANDO <- SingleCellExperiment::SingleCellExperiment(list(counts=pando_Peaks_matrix))

In [62]:
PeakMatrix_PANDO

class: SingleCellExperiment
dim: 459186 49470
metadata(0):
assays(1): counts
rownames(459186): chr1-181291-181601 chr1-184649-184672 ...
  chrY-19744940-19744980 chrY-20575517-20575724
rowData names(0):
colnames(49470): 10X280_1:CAGATTCAGCAGCTCA 10X365_2:ACCAATATCAATGACC
  ... 10X346_4:CGCTGTGCACGTAATT 10X406_4:GAGAAACGTGGTGAGA
colData names(0):
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):

In [63]:
PeakMatrix_PANDO@assays@data$counts %>% class()

[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"

In [64]:
identical(colnames(PeakMatrix), colnames(PeakMatrix_PANDO))

[1] TRUE

In [65]:
PeakMatrix_PANDO %>% 
    saveRDS(here::here('r_objects', 'PeakMatrix_w_Pando_used_peak_regions.RDS'))

In [66]:
matched_indices <- match(Pando_regulon_df$region, rownames(PeakMatrix_PANDO))

In [67]:
matched_indices %>% head()

[1] 446220 446220 446220 446220 446220 446220

In [68]:
matched_indices %>% anyNA()

[1] FALSE

In [73]:
table(rownames(PeakMatrix_PANDO)[matched_indices] == Pando_regulon_df$region)

   TRUE
3696132

In [74]:
# add the indices to the Pando regulon df:

Pando_regulon_df$idxATAC <- matched_indices

In [75]:
Pando_regulon_df %>% head()

  tf     target region               term                        estimate
1 NFIB   NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:NFIB    0.038513008
2 ZFPM2  NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:ZFPM2  -0.007733542
3 SOX11  NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:SOX11   0.065692288
4 SREBF2 NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:SREBF2 -0.011474373
5 NFIX   NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:NFIX    0.038547242
6 PRDM16 NLGN4X chrX-4850308-4850651 chrX_4850308_4850651:PRDM16  0.102150764
  std_err    statistic  pval        padj       corr      idxATAC
1 0.01176352  3.2739367 0.001061345 0.02420174 0.2650796 446220
2 0.01592443 -0.4856401 0.627224560 0.88962096 0.1124816 446220
3 0.02031582  3.2335530 0.001223423 0.02697227 0.1387585 446220
4 0.01963357 -0.5844262 0.558936340 0.86081834 0.1436841 446220
5 0.02219537  1.7367245 0.082442149 0.40317544 0.2110484 446220
6 0.07533459  1.3559609 0.175117909 0.56993025 0.1478573 446220

In [78]:
Pando_regulon_df %>% 
    saveRDS(here::here('r_objects', 'Pando_coef_DF_as_regulon_DF.RDS'))

In [79]:
# In this example, we apply Wilcoxon test on cell aggregates of 10 cells. 
# We use the Wilcoxon weight method  because we are interested in computing 
# cell type-specific weights.

set.seed(1010)

Pando_regulon_df_weighted <- epiregulon::addWeights(regulon = Pando_regulon_df,
                                expMatrix  = GeneExpressionMatrix,
                                exp_assay  = "logcounts",
                                peakMatrix = PeakMatrix_PANDO,
                                peak_assay = "counts",
                                clusters = GeneExpressionMatrix$main_cell_types_renamed,
                                aggregateCells = TRUE,
                                min_targets = 10, # Calc. for TFs with minimum num. of targets. Default is 10. 
                                method = "wilcox",
                                useDim = "PCA")

adding weights using wilcoxon...

performing pseudobulk using an average of 10 cells

In [80]:
Pando_regulon_df_weighted %>% dim()

[1] 3679888      12

In [81]:
Pando_regulon_df_weighted %>% head()

DataFrame with 6 rows and 12 columns
           tf      target                 region                   term
  <character> <character>            <character>            <character>
1        ADNP      TMSB4X chrX-11896063-11896220 chrX_11896063_118962..
2        ADNP      TMSB4X chrX-11941565-11941909 ADNP:chrX_11941565_1..
3        ADNP      TMSB4X chrX-11952241-11952586 ADNP:chrX_11952241_1..
4        ADNP      TMSB4X chrX-12373690-12373940 ADNP:chrX_12373690_1..
5        ADNP      TMSB4X chrX-12467579-12467676 ADNP:chrX_12467579_1..
6        ADNP      TMSB4X chrX-12701662-12701873 ADNP:chrX_12701662_1..
     estimate   std_err statistic      pval      padj      corr   idxATAC
    <numeric> <numeric> <numeric> <numeric> <numeric> <numeric> <integer>
1 -0.00849715 0.0309463 -0.274577  0.783642  0.944356  -0.12546    447107
2 -0.01506174 0.0255604 -0.589260  0.555689  0.859407  -0.12546    447109
3 -0.00241433 0.0128102 -0.188469  0.850510  0.963502  -0.12546    447112
4 -0.01123204 0.0238822 -0.470310  0.638136  0.893895  -0.12546    447148
5  0.01309425 0.0258123  0.507286  0.611956  0.883253  -0.12546    447165
6  0.01342345 0.0184689  0.726812  0.467345  0.816032  -0.12546    447177
                                 weight
                               <matrix>
1  0.00484705:-0.02788725:0.0349433:...
2  0.13442963:-0.00192452:0.0548120:...
3  0.21822911: 0.03173178:0.0388712:...
4 -0.03597643:-0.00782800:0.0327431:...
5 -0.00210910:-0.05488041:0.1070644:...
6  0.02776697: 0.00784104:0.1136336:...

In [82]:
Pando_regulon_df_weighted$weight %>% head()

     all          endothelial_cells immune_cells neurons
[1,]  0.004847052 -0.027887246      0.03494331   0.04816665
[2,]  0.134429633 -0.001924516      0.05481197   0.02528538
[3,]  0.218229109  0.031731785      0.03887121   0.05050917
[4,] -0.035976431 -0.007827999      0.03274314   0.02895804
[5,] -0.002109098 -0.054880414      0.10706443   0.11953608
[6,]  0.027766972  0.007841038      0.11363364   0.11082368
     oligodendrocyte_precursors pericytes  radial_and_glioblast
[1,]  0.07130755                0.06814199  0.01612083
[2,] -0.02593276                0.22657550  0.06060241
[3,]  0.06260286                0.37195771 -0.01111759
[4,] -0.03956958                0.02576604 -0.02327600
[5,] -0.01564294                0.03890237  0.03112337
[6,]  0.13902038                0.09392432  0.08920059
     vascular_leptomeningeal_cells_vlmc vascular_smooth_muscle_cells
[1,]  0.11408579                        0.0000000
[2,]  0.11339008                        0.2933111
[3,] -0.02241350                        0.2641663
[4,] -0.06818028                        0.0000000
[5,]  0.11144397                        0.2241976
[6,]  0.08055204                        0.1045440
     ventricular_zone_progenitor_cells_vz_prog
[1,]  0.00000000
[2,]  0.21938173
[3,]  0.00000000
[4,] -0.16453630
[5,]  0.05484543
[6,] -0.20712215

In [83]:
Pando_regulon_df_weighted$weight %>% summary()

      all            endothelial_cells   immune_cells         neurons
 Min.   :-0.606283   Min.   :-0.59012   Min.   :-0.33129   Min.   :-0.423114
 1st Qu.:-0.002367   1st Qu.:-0.01008   1st Qu.: 0.01029   1st Qu.: 0.008282
 Median : 0.071642   Median : 0.05156   Median : 0.05311   Median : 0.049676
 Mean   : 0.090027   Mean   : 0.06896   Mean   : 0.06823   Mean   : 0.060768
 3rd Qu.: 0.170074   3rd Qu.: 0.13464   3rd Qu.: 0.10746   3rd Qu.: 0.096880
 Max.   : 0.894228   Max.   : 0.99902   Max.   : 0.99954   Max.   : 0.999483
 oligodendrocyte_precursors   pericytes         radial_and_glioblast
 Min.   :-0.56144           Min.   :-0.370435   Min.   :-0.50512
 1st Qu.: 0.01632           1st Qu.: 0.005453   1st Qu.: 0.01987
 Median : 0.07196           Median : 0.055334   Median : 0.05963
 Mean   : 0.08297           Mean   : 0.074284   Mean   : 0.07184
 3rd Qu.: 0.13131           3rd Qu.: 0.116401   3rd Qu.: 0.10922
 Max.   : 0.99889           Max.   : 0.999228   Max.   : 0.99948
 vascular_leptomeningeal_cells_vlmc vascular_smooth_muscle_cells
 Min.   :-0.47203                   Min.   :-0.99103
 1st Qu.: 0.00000                   1st Qu.: 0.00000
 Median : 0.05931                   Median : 0.04757
 Mean   : 0.07018                   Mean   : 0.09203
 3rd Qu.: 0.12887                   3rd Qu.: 0.19723
 Max.   : 0.99785                   Max.   : 0.99103
 ventricular_zone_progenitor_cells_vz_prog
 Min.   :-0.98473
 1st Qu.: 0.00000
 Median : 0.00000
 Mean   : 0.09165
 3rd Qu.: 0.21975
 Max.   : 0.98473

In [84]:
Pando_regulon_df_weighted %>% 
    saveRDS(here::here('r_objects', 'Pando_regulon_df_cell_type_weighted.RDS'))

In [87]:
epiregulon::calculateActivity %>% args()

function (expMatrix = NULL, exp_assay = "logcounts", regulon = NULL,
    normalize = FALSE, mode = "weight", method = c("weightedmean",
        "aucell"), genesets = NULL, clusters = NULL, FUN = c("mean",
        "sum"), ncore = 1, BPPARAM = BiocParallel::SerialParam())
NULL

====================================

Next, I will continue with calculation of TF activity scores.

====================================

In [88]:
sessionInfo()

R version 4.4.2 (2024-10-31)
Platform: x86_64-unknown-linux-gnu
Running under: Red Hat Enterprise Linux 9.4 (Plow)

Matrix products: default
BLAS/LAPACK: /gnu/store/mj1kw87qd3m1q7r4844adkn5hifx8k6a-openblas-0.3.20/lib/libopenblasp-r0.3.20.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=C          LC_NUMERIC=C        LC_TIME=C
 [4] LC_COLLATE=C        LC_MONETARY=C       LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C          LC_NAME=C           LC_ADDRESS=C
[10] LC_TELEPHONE=C      LC_MEASUREMENT=C    LC_IDENTIFICATION=C

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Pando_1.1.1    magrittr_2.0.3

loaded via a namespace (and not attached):
  [1] RcppAnnoy_0.0.22            splines_4.4.2
  [3] later_1.4.1                 pbdZMQ_0.3-11
  [5] bitops_1.0-9                tibble_3.2.1
  [7] polyclip_1.10-7             fastDummies_1.7.5
  [9] lifecycle_1.0.4             edgeR_4.2.2
 [11] rprojroot_2.0.4             globals_0.16.3
 [13] lattice_0.22-6              pals_1.9
 [15] MASS_7.3-61                 backports_1.5.0
 [17] limma_3.60.6                plotly_4.10.4
 [19] metapod_1.12.0              httpuv_1.6.15
 [21] Seurat_5.2.1                sctransform_0.4.1
 [23] spam_2.11-1                 sp_2.2-0
 [25] spatstat.sparse_3.1-0       reticulate_1.40.0
 [27] cowplot_1.1.3               mapproj_1.2.11
 [29] pbapply_1.7-2               RColorBrewer_1.1-3
 [31] maps_3.4.2                  abind_1.4-8
 [33] Rtsne_0.17                  GenomicRanges_1.56.2
 [35] purrr_1.0.4                 RCurl_1.98-1.16
 [37] ggraph_2.2.1                BiocGenerics_0.50.0
 [39] tweenr_2.0.3                GenomeInfoDbData_1.2.12
 [41] IRanges_2.38.1              S4Vectors_0.42.1
 [43] ggrepel_0.9.6               irlba_2.3.5.1
 [45] listenv_0.9.1               spatstat.utils_3.1-2
 [47] goftest_1.2-3               RSpectra_0.16-2
 [49] dqrng_0.4.1                 spatstat.random_3.3-2
 [51] fitdistrplus_1.2-2          parallelly_1.42.0
 [53] DelayedMatrixStats_1.26.0   RcppRoll_0.3.1
 [55] codetools_0.2-20            DelayedArray_0.30.1
 [57] scuttle_1.14.0              ggforce_0.4.2
 [59] tidyselect_1.2.1            UCSC.utils_1.0.0
 [61] farver_2.1.2                ScaledMatrix_1.12.0
 [63] viridis_0.6.5               matrixStats_1.5.0
 [65] stats4_4.4.2                base64enc_0.1-3
 [67] spatstat.explore_3.3-4      jsonlite_1.8.8
 [69] BiocNeighbors_1.22.0        tidygraph_1.3.1
 [71] progressr_0.15.1            ggridges_0.5.6
 [73] survival_3.7-0              tools_4.4.2
 [75] ica_1.0-3                   Rcpp_1.0.14
 [77] glue_1.7.0                  gridExtra_2.3
 [79] SparseArray_1.4.8           here_1.0.1
 [81] epiregulon_1.0.1            MatrixGenerics_1.16.0
 [83] GenomeInfoDb_1.40.1         IRdisplay_1.1
 [85] dplyr_1.1.4                 withr_3.0.2
 [87] fastmap_1.2.0               bluster_1.14.0
 [89] fansi_1.0.6                 ggpointdensity_0.1.0
 [91] rsvd_1.0.5                  digest_0.6.37
 [93] R6_2.5.1                    mime_0.12
 [95] colorspace_2.1-1            scattermore_1.2
 [97] gtools_3.9.5                tensor_1.5
 [99] dichromat_2.0-0.1           spatstat.data_3.1-4
[101] utf8_1.2.4                  tidyr_1.3.1
[103] generics_0.1.3              data.table_1.16.4
[105] graphlayouts_1.1.1          httr_1.4.7
[107] htmlwidgets_1.6.4           S4Arrays_1.4.1
[109] uwot_0.2.2                  pkgconfig_2.0.3
[111] gtable_0.3.6                lmtest_0.9-40
[113] SingleCellExperiment_1.26.0 XVector_0.44.0
[115] htmltools_0.5.8.1           dotCall64_1.2
[117] SeuratObject_5.0.2          scales_1.3.0
[119] Biobase_2.64.0              png_0.1-8
[121] spatstat.univar_3.1-1       scran_1.32.0
[123] Signac_1.14.0               reshape2_1.4.4
[125] uuid_1.2-1                  checkmate_2.3.2
[127] nlme_3.1-166                repr_1.1.7
[129] zoo_1.8-12                  cachem_1.1.0
[131] stringr_1.5.1               KernSmooth_2.23-24
[133] parallel_4.4.2              miniUI_0.1.1.1
[135] pillar_1.9.0                grid_4.4.2
[137] vctrs_0.6.5                 RANN_2.6.2
[139] promises_1.3.2              BiocSingular_1.20.0
[141] beachmat_2.20.0             xtable_1.8-4
[143] cluster_2.1.6               evaluate_0.24.0
[145] locfit_1.5-9.11             Rsamtools_2.20.0
[147] cli_3.6.3                   compiler_4.4.2
[149] rlang_1.1.4                 crayon_1.5.3
[151] future.apply_1.11.3         plyr_1.8.9
[153] stringi_1.8.4               BiocParallel_1.38.0
[155] viridisLite_0.4.2           deldir_2.0-4
[157] Biostrings_2.72.1           munsell_0.5.1
[159] lazyeval_0.2.2              spatstat.geom_3.3-5
[161] Matrix_1.7-0                IRkernel_1.3.2
[163] RcppHNSW_0.6.0              patchwork_1.3.0
[165] sparseMatrixStats_1.16.0    future_1.34.0
[167] ggplot2_3.5.1               statmod_1.5.0
[169] shiny_1.10.0                SummarizedExperiment_1.34.0
[171] ROCR_1.0-11                 igraph_2.1.4
[173] memoise_2.0.1               fastmatch_1.1-4